version: '3.6'

services:
    gopoll:
        image: golang:latest
        build:
            context: .
            dockerfile: ./src/gopoll/Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./:/go/src/github.com/wyrdnixx/votegovue                  
        networks:
            app-network:                
                aliases:
                - app.app.local
networks:
  app-network:
    driver: bridge